/**
 * Cross-module shared scalar types.
 * Modules MUST import shared types from here rather than redefining them.
 */

/** ISO 8601 datetime string (e.g. "2026-05-10T12:34:56.000Z"). */
export type ISO8601 = string;

/** Lowercase, trimmed email address. Validate at the boundary; trust within. */
export type EmailAddress = string;

/** Stable opaque ID generated by @bdas/id (e.g. "mem_kFdL9Rk23m..."). */
export type Id = string;

/** Money in integer cents — never use floats for money. */
export type MoneyCents = number;

/** ISO-4217 currency code. v1 is EUR-only; type allows future flexibility. */
export type CurrencyCode = "EUR";

/** Discriminated result type for service-layer functions that prefer not to throw. */
export type Result<T, E = Error> =
  | { readonly ok: true; readonly value: T }
  | { readonly ok: false; readonly error: E };

export const ok = <T>(value: T): Result<T, never> => ({ ok: true, value });
export const err = <E>(error: E): Result<never, E> => ({ ok: false, error });
