/**
 * Einmaliger Generator: statischer FAQ-Content → modules/faq/migrations/0002_seed.sql.
 * Ausführen mit: pnpm --filter web exec tsx scripts/generate-faq-seed.ts
 * Das erzeugte SQL wird committet; dieses Skript bleibt als Dokumentation liegen.
 */
import { writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { SECTIONS, type FaqBlock } from "../content/faq";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const TOPICS = [
  ["events", "Events"],
  ["dateien", "Dateien"],
  ["administration", "Administration"],
  ["profil", "Profil & Konto"],
  ["gruppen", "Gruppen"],
] as const;

/**
 * Grobe, manuelle Themen-Zuordnung je statischer Entry-ID — bewusst nicht
 * erschöpfend. Der Bundesvorstand verfeinert das später im Editor (Spec §8).
 * Ids ohne Eintrag hier bleiben ohne Thema (topic_id NULL).
 */
const TOPIC_BY_ENTRY_ID: Readonly<Record<string, (typeof TOPICS)[number][0]>> = {
  "registrierung-login": "profil",
  rollenmodell: "administration",
  "scope-switcher": "administration",
  "zugriff-sicherheit": "administration",
  "account-praeferenzen": "profil",
  overview: "administration",
  "mitglieder-events-gruppen": "administration",
  "gruppen-verwalten": "gruppen",
  rollenvergabe: "administration",
  pool: "administration",
  dateien: "dateien",
  "lb-uebersicht-roster": "administration",
  "lb-events": "events",
  "lb-profil-vs-seite": "gruppen",
  "lb-dateien": "dateien",
  "lb-grenzen": "administration",
  "lead-was-zusaetzlich": "administration",
  "lead-grenzen": "administration",
  "eo-scope": "events",
  "pe-scope": "gruppen",
  profil: "profil",
  events: "events",
  gruppenwechsel: "gruppen",
  alumni: "profil",
};

function blockToTiptap(b: FaqBlock): unknown {
  if (b.kind === "p") return { type: "paragraph", content: [{ type: "text", text: b.text }] };
  if (b.kind === "steps")
    return {
      type: "orderedList",
      content: b.items.map((item) => ({
        type: "listItem",
        content: [{ type: "paragraph", content: [{ type: "text", text: item }] }],
      })),
    };
  // link → Absatz mit Link-Mark
  return {
    type: "paragraph",
    content: [{ type: "text", text: b.label, marks: [{ type: "link", attrs: { href: b.href } }] }],
  };
}

const esc = (s: string) => s.replace(/'/g, "''");

// Statischer Content hat eine Id-Kollision (bundesvorstand.ts und mitglieder.ts
// verwenden beide "dateien"), faq_entries.id ist aber global eindeutig (PK).
// Erstes Vorkommen (Sections-Reihenfolge: allgemein, bundesvorstand, vorstand,
// mitglieder) behält die Id unverändert — das ist auch die Id, die /faq#dateien
// im heutigen statischen Markup tatsächlich trifft (erstes Element im DOM).
// Jede weitere Kollision wird auf "<section>-<id>" disambiguiert, statt den
// Eintrag über ON CONFLICT DO NOTHING stillschweigend zu verlieren.
const seenIds = new Set<string>();
function dedupeId(id: string, sectionKey: string): string {
  if (!seenIds.has(id)) {
    seenIds.add(id);
    return id;
  }
  const alt = `${sectionKey}-${id}`;
  console.warn(
    `[generate-faq-seed] duplicate static entry id "${id}" — disambiguated to "${alt}" for section "${sectionKey}". Static content left unchanged; only the seed row got a new id.`,
  );
  seenIds.add(alt);
  return alt;
}

const lines: string[] = [
  "-- Generated by apps/web/scripts/generate-faq-seed.ts — do not edit by hand.",
];
for (const [i, [id, name]] of TOPICS.entries())
  lines.push(
    `INSERT INTO faq_topics (id, name, position) VALUES ('${id}', '${esc(name)}', ${i}) ON CONFLICT (id) DO NOTHING;`,
  );

let entryCount = 0;
for (const section of Object.values(SECTIONS)) {
  const flat = [
    ...section.entries.map((e) => ({ e, subgroup: "NULL" })),
    ...(section.subgroups ?? []).flatMap((sub) =>
      sub.entries.map((e) => ({ e, subgroup: `'${sub.id}'` })),
    ),
  ];
  for (const [pos, { e, subgroup }] of flat.entries()) {
    const id = dedupeId(e.id, section.key);
    const topic = TOPIC_BY_ENTRY_ID[e.id];
    const topicId = topic ? `'${topic}'` : "NULL";
    const body = JSON.stringify({ type: "doc", content: e.body.map(blockToTiptap) });
    lines.push(
      `INSERT INTO faq_entries (id, section, subgroup, topic_id, question, body, status, position) ` +
        `VALUES ('${esc(id)}', '${section.key}', ${subgroup}, ${topicId}, '${esc(e.question)}', '${esc(body)}'::jsonb, 'published', ${pos}) ` +
        `ON CONFLICT (id) DO NOTHING;`,
    );
    entryCount++;
  }
}

writeFileSync(
  path.join(__dirname, "..", "..", "..", "modules", "faq", "migrations", "0002_seed.sql"),
  lines.join("\n") + "\n",
);
console.log(
  `wrote ${lines.length - 1} statements (${TOPICS.length} topics, ${entryCount} entries)`,
);
